# Generated by Django 3.1.4 on 2020-12-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_description', models.TextField()),
                ('slider_created_by', models.IntegerField()),
                ('slider_created_at', models.DateTimeField()),
            ],
        ),
    ]
