# Generated by Django 3.0.5 on 2020-12-09 09:30

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('slider_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_description', models.TextField()),
                ('slider_created_by', models.IntegerField()),
                ('slider_created_at', models.DateTimeField()),
            ],
        ),
    ]
