# Generated by Django 3.1.4 on 2020-12-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingApp', '0005_auto_20201225_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_images',
            field=models.ImageField(upload_to='slider/'),
        ),
    ]
