# Generated by Django 3.1.4 on 2020-12-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingApp', '0006_auto_20201225_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_images',
            field=models.ImageField(default=0, upload_to='event/'),
            preserve_default=False,
        ),
    ]
