# Generated by Django 3.1.4 on 2020-12-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingApp', '0007_event_event_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryevent',
            options={'verbose_name_plural': 'Kategori'},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id_kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingApp.categoryevent', verbose_name='Kategori'),
        ),
    ]
