# Generated by Django 3.1.4 on 2020-12-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingApp', '0009_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_nama_pria', models.CharField(max_length=255, verbose_name='Nama Mempelai Pria')),
                ('setting_nama_perempuan', models.SlugField(max_length=255, unique=True, verbose_name='Nama Mempelai Perempuan')),
                ('setting_schedule', models.DateTimeField()),
                ('setting_email', models.CharField(max_length=255)),
                ('setting_contact', models.CharField(max_length=255)),
                ('setting_footer_title', models.CharField(max_length=255)),
                ('setting_footer_content', models.TextField()),
                ('setting_story_content', models.TextField()),
            ],
        ),
    ]
