# Generated by Django 3.1.4 on 2020-12-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingApp', '0010_setings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_tamu', models.CharField(max_length=255, verbose_name='Nama Tamu')),
                ('invitation_pasangan_tamu', models.SlugField(max_length=255, unique=True, verbose_name='Nama Rekan Tamu')),
                ('invitaion_email', models.CharField(max_length=255, verbose_name='E-mail')),
            ],
        ),
    ]
