# Generated by Django 3.1.4 on 2020-12-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingApp', '0011_invitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='invitation_pasangan_tamu',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nama Rekan Tamu'),
        ),
    ]
