# Generated by Django 3.1.4 on 2020-12-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingApp', '0012_auto_20201226_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='setings',
            name='setting_location',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
