# Generated by Django 3.1.4 on 2020-12-26 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingApp', '0013_setings_setting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id_kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to='weddingApp.categoryevent', verbose_name='Kategori'),
        ),
    ]
