# Generated by Django 3.1.4 on 2020-12-26 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weddingApp', '0015_auto_20201226_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-12-27 08:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
